project:
  type: website

website:
  title: "About My English"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: lm.qmd
        text: Language Models

format:
  html:
    theme: cosmo
